# Generated by Django 2.1.7 on 2021-01-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
